# fly.toml app configuration file generated for shipout-consumer on 2026-03-05T00:08:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shipout-consumer'
primary_region = 'cdg'

[env]
  NODE_ENV = "production"

[processes]
  app = "npm run consumer"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
